### ISSUE TITLE
What is the plus over featherjs channels?

### ISSUE THREAD

**Issue by musicformellons** [feathersjs-ecosystem/feathers-reactive#132]
I am (slightly) familiar with RxJS and also with Featherjs. What is the exact advantage of using feathers-reactive, as feathersjs with channels is already dealing with realtime updates? Or am I missing something?

I found [this article](https://medium.com/@sean.nicholas/feathers-reactive-with-angular-universal-756f9cd1bd14). This gives me the impression it might be a solution when using Server Side Rendering!? Is that it?

**Comment by daffl** [comment]
They are both quite different. Channels determine which client is going to receive which real-time events on the server.

`feathers-reactive` turns real-time events into an obversable stream of data. Instead of having to do something like the following everywhere:

```js
const messages = app.service('messages');
const messagesPage = await service.find();

messages.on('created', msg => {
  messages.data.push(msg);
  renderView(messages);
});

messages.on('removed', msg => {
  // Remove data
  messages.data = messages.data.filter(current => current.id !== msg.id);
  renderView(messages);
});

// Update patched messages
service.on('patched', message => {
  // Update patched messages
  messages.data = messages.data.map(old => {
    if(old.id === message.id) {
      return message;
    }

    return old;
  });

  renderView(messages);
});
```

You can just do

```
app.service('messages').find().watch().subscribe(messages => renderView(messages);
```

Have a look at [this video](https://www.youtube.com/watch?v=IOwilPI4LFg&) which shows how to use it to built a real-time React application.

**Comment by musicformellons** [comment]
Cool! Any suggestions for the client side when using Vue.js (with Vuex)?! I saw vue-rx, is that a requirement when using feathers-reactive, or not really?
