### ISSUE TITLE
Consuming service with server-side pagination & infinite loading

### ISSUE THREAD

**Issue by sambostock** [feathersjs-ecosystem/feathers-reactive#44]
(Posting here following discussion on feathersjs.slack.com)

Given a service which paginates server side, what would be the appropriate way to consume it, in the following scenario:

We want to create an infinite scrolling list, which updates in real-time, as resources are created/updated/removed.

Currently, using something like

```
myService.find().subscribe(response => console.log(response));
```

initially yields the response from the server, say:

```
{
  data: [
    { id: '1111' },
    { id: '2b2b' },
    { id: '5aef' },
    { id: '3333' },
    { id: '4444' }
],
  limit: 5,
  skip: 0,
  total: 5
}
```

If we then create a resource with an `id` of `'5555'` (say by hitting the server with Postman), the same observable yields again:

```
{
  data: [
    { id: '1111' },
    { id: '2b2b' },
    { id: '3333' },
    { id: '4444' },
    { id: '5555' }
  ],
  limit: 5,
  skip: 0,
  total: 6
}
```

Notice the results are now sorted by `id`.

If we create another resource, with `id` of `'6666'`, the observable yields:

```
{
  data: [
    { id: '1111' },
    { id: '2b2b' },
    { id: '3333' },
    { id: '4444' },
    { id: '5555' }
  ],
  limit: 5,
  skip: 0,
  total: 7
}
```

So the observable is sorting by `id`, and enforcing the `$limit`, which we didn't pass to it (it was in the server's response). This behaviour is not ideal for implementing an infinite list. There seems to be no good pattern for consuming such a service like this.

@daffl (on Slack):

> I think there are two things:
> - Allow non paginated reactive lists (right now they are truncated based on $limit)
> - Have a code sample for creating an infinite loading observable

**Comment by sambostock** [comment]
### Example scenario:

- Server side page size of 3
- User application displays ordered list with infinite scroll

1. User opens app, triggers initial load

        Server DB state:   0, 1, 2, 3, 4, 5, 6, 7
        Client list:                      5, 6, 7

1. User scrolls down, triggers load more

        Server DB state: 0, 1, 2, 3, 4, 5, 6, 7
        Client list:           2, 3, 4, 5, 6, 7

1. User creates `8`

        Server DB state: 0, 1, 2, 3, 4, 5, 6, 7, 8
        Client list:           2, 3, 4, 5, 6, 7, 8

1. Other user removes `4`

        Server DB state: 0, 1, 2, 3,    5, 6, 7, 8
        Client list:           2, 3,    5, 6, 7, 8

1. Other user updates (`1` -> `9`)

        Server DB state: 0,    2,       5, 6, 7, 8, 9
        Client list:           2,       5, 6, 7, 8, 9

1. User scrolls down more, triggers load more

        Server DB state: 0,    2,       5, 6, 7, 8, 9
        Client list:     0,    2,       5, 6, 7, 8, 9

**Comment by harangue** [comment]
I think this problem is very much solvable without changing feathers-reactive, it just requires some fancy observable work. I would also contend, however, that from a user's perspective dynamically inserting items in the list is not going to be a very good experience for them (Facebook doesn't attempt this, for instance, it just notifies a user that new items are available). In that case, the problem actually becomes quite simple.

```
Observable
  .fromEvent(reachedBottomOfThePage)
  .scan((loadMoreCount) => {
    return loadMoreCount++;
  }, 0)
  .flatMap((loadMoreCount) =>
    app.service('/foo').find({ $skip: loadMoreCount * PAGE_SIZE })
  )
  .scan((prev, {result}) => {
    // You can also add some code here to check for duplicate IDs and such
    return [...prev, result];
  }, []);
```

The trick here is that you don't want to have each of your items being piped through the observable, but rather, an array containing all of your data.

Again, I'm fairly certain you could also accomplish this dynamic insertion ideal with pure observables, but it probably won't be the most maintainable way to model it (you probably want removal animation, and some sort of indicator to the user that an item has been inserted above their scroll position, etc.) Nonetheless, here's my (untested) hypothesis of what it would look like:

```
const liveChanges$ = Observable
  .fromEvent(app.service('/foo).find(), 'create')
});

Observable
  .fromEvent(document, 'reachedBottomOfThePage')
  .scan((loadMoreCount) => {
    return loadMoreCount++;
  }, 0)
  .flatMap((loadMoreCount) =>
    app.service('/foo').find({
      $skip: loadMoreCount * PAGE_SIZE,
      rx: {
        listStrategy: 'never'
      }
    })
  )
  .scan((prev, {result}) => {
    // You can also add some code here to check for duplicate IDs and such
    return [...prev, result];
  }, [])
  .combineLatest(liveChanges$, (static, newItem) => {
    // Filter array to make sure that it doesn't already contain the item
    const matches = static.filter((x) => x.id === newItem.id);
    if (matches.length > 0) return static;

    // Insert newItem and sort our array
    const sorted = [...static, newItem].sort();

    // If the newItem is the last item of our array, we haven't reached it
    // in our infinite scroll. Remove it.
    if (sorted[sorted.length - 1] === newItem) return static;

    return sorted;
  });
```

Of course, you're gonna have to write some more code for `patch`, and `update` and such, but some of the concerns associated with this are so application-specific that I'm hesitant to say that it's feathers-reactive's job to solve them.
